services:
  devcontainer:
    command: sh -c 'while sleep 1; do :; done'
    image: public.ecr.aws/v6m6o3k4/haskell:9.2.4-a853e18e0505bc9590dd6eaa31231ae2610fbfa8
    init: true
    volumes:
      - ..:/workspaces/witch
      - cabal:/home/haskell/.cabal
      - cabal-store:/cabal-store
    working_dir: /workspaces/witch
volumes:
  cabal: null
  cabal-store:
    external: true
